-- Staging: expõe a tabela Bronze como fonte para os modelos Silver/Gold
-- Materializado como view — sem custo de armazenamento extra

SELECT
    id,
    nu_inscricao,
    nu_ano,
    tp_faixa_etaria,
    tp_sexo,
    tp_estado_civil,
    tp_cor_raca,
    tp_nacionalidade,
    tp_st_conclusao,
    tp_ano_concluiu,
    tp_escola,
    tp_ensino,
    in_treineiro,
    co_municipio_esc,
    no_municipio_esc,
    co_uf_esc,
    sg_uf_esc,
    tp_dependencia_adm_esc,
    tp_localizacao_esc,
    tp_sit_func_esc,
    co_municipio_prova,
    no_municipio_prova,
    co_uf_prova,
    sg_uf_prova,
    nu_nota_cn,
    nu_nota_ch,
    nu_nota_lc,
    nu_nota_mt,
    nu_nota_redacao,
    tp_presenca_cn,
    tp_presenca_ch,
    tp_presenca_lc,
    tp_presenca_mt,
    tp_lingua,
    tp_status_redacao,
    q001, q002, q003, q004, q005, q006,
    ingested_at
FROM {{ source('bronze', 'enem_2023') }}
